name: CI & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Deploy via SSH into EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Navigating to project directory..."
            cd /home/ubuntu/Tour-Project

            echo "Pulling latest code..."
            git pull origin main

            echo "Stopping old container..."
            docker stop tour-frontend || true
            docker rm tour-frontend || true

            echo "Building Docker image..."
            docker build -t tour-frontend .

            echo "Running new container..."
            docker run -d -p 8080:80 --name tour-frontend tour-frontend
